title: Porcelain
description: Switch editors, not your Git workflow.
url: https://porcelain.kenroy.dev
baseurl: ""
markdown: kramdown
kramdown:
  input: GFM
  smart_quotes: [apos, apos, quot, quot]
  hard_wrap: false
exclude:
  - README.md
  - _tools
  - _preview
  - Gemfile
  - Gemfile.lock
