export const IdeaGitErrorCode = {
  REPO_NOT_FOUND: "REPO_NOT_FOUND",
  INVALID_REF: "INVALID_REF",
  BRANCH_NOT_FOUND: "BRANCH_NOT_FOUND",
  BRANCH_NO_UPSTREAM: "BRANCH_NO_UPSTREAM",
  BRANCH_CHECKED_OUT_IN_WORKTREE: "BRANCH_CHECKED_OUT_IN_WORKTREE",
  BRANCH_NON_FAST_FORWARD: "BRANCH_NON_FAST_FORWARD",
  BRANCH_NOT_FULLY_MERGED: "BRANCH_NOT_FULLY_MERGED",
  UNMERGED_PATHS: "UNMERGED_PATHS",
  INDEX_PREPARE_FAILED: "INDEX_PREPARE_FAILED",
  INDEX_RESTORE_FAILED: "INDEX_RESTORE_FAILED",
  PARTIAL_FILE_SELECTION_UNSUPPORTED: "PARTIAL_FILE_SELECTION_UNSUPPORTED",
  UNSUPPORTED_SHELF_CONTENT: "UNSUPPORTED_SHELF_CONTENT",
  COMMIT_REJECTED: "COMMIT_REJECTED",
  OPERATION_CANCELLED: "OPERATION_CANCELLED",
} as const;

export type IdeaGitErrorCode =
  (typeof IdeaGitErrorCode)[keyof typeof IdeaGitErrorCode];

export class IdeaGitError extends Error {
  constructor(
    readonly code: IdeaGitErrorCode,
    message: string,
    readonly recovery?: string,
  ) {
    super(message);
    this.name = "IdeaGitError";
  }
}
